sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hagerelhalaby/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hagerelhalaby/docker-react npm test